/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "@nm/flatpickr/**/*.js",
    "@nm/flyonui/dist/js/*.js",
    "./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}",
  ],
  flyonui: {
    vendors: true,
    themes: [
      "corporate",
      "luxury",
      // {
      //   light: {
      //     primary: "#808080",
      //     secondary: "#4d4d4d",
      //     accent: "#1a1a1a",
      //     neutral: "#f2f2f3",
      //     content: "#7d7d7d",
      //     info: "#1c92f2",
      //     success: "#009485",
      //     warning: "#ff9900",
      //     error: "#ff5724",
      //     "base-100": "#ffffff",
      //     "base-200": "#ffffff",
      //     "base-300": "#ffffff",
      //     "--rounded-box": ".25rem",
      //     "--rounded-btn": ".25rem",
      //     "--rounded-tooltip": "1.9rem",
      //     "--animation-btn": "0.25s",
      //     "--animation-input": "0.2s",
      //     "--tab-border": "1px",
      //     "--tab-radius": "0.5rem",
      //     "--border-btn": "1px",
      //     "--btn-focus-scale": "0.95",
      //   },
      //   dark: {
      //     primary: "#ffffff",
      //     secondary: "#ffffff",
      //     accent: "#ffffff",
      //     neutral: "#333333",
      //     content: "#ffffff",
      //     info: "#0000ff",
      //     success: "#008000",
      //     warning: "#ffff00",
      //     error: "#ff0000",
      //     "base-100": "#000000",
      //     "base-200": "#333333",
      //     "base-300": "#4d4d4d",
      //     "--rounded-box": ".25rem",
      //     "--rounded-btn": ".25rem",
      //     "--rounded-tooltip": "1.9rem",
      //     "--animation-btn": "0.25s",
      //     "--animation-input": "0.2s",
      //     "--tab-border": "1px",
      //     "--tab-radius": "0.5rem",
      //     "--border-btn": "1px",
      //     "--btn-focus-scale": "0.95",
      //   },
      // },
    ],
    darkTheme: "luxury",
  },
  theme: {
    extend: {},
  },
  plugins: [require("flyonui"), require("flyonui/plugin")],
};
