// Generated by Wrangler on Sat Apr 06 2024 22:48:02 GMT-0600 (Central Standard Time)
// by running `wrangler types`

interface Env {
	ENV: "development";
	GOOGLE_CLIENT_ID: "776680141608-b886bq9oki9bppl259pvptilcoa0bg97.apps.googleusercontent.com";
	GOOGLE_SECRET: "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";
	SESSION_SECRET: "MfT4ZHeYadduUVB6";
	TURSO_DB_URL: " http://127.0.0.1:8080";
}
