name = "ecommerce-admin"
compatibility_date = "2024-04-06"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#environment-variables

[vars]
ENV='development'
GOOGLE_CLIENT_ID = '776680141608-b886bq9oki9bppl259pvptilcoa0bg97.apps.googleusercontent.com'
GOOGLE_SECRET = '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'
SESSION_SECRET = 'MfT4ZHeYadduUVB6'
# TURSO_DB_URL = "libsql://ecommerce-admin-falvarador.turso.io"
TURSO_DB_URL = "http://127.0.0.1:8080"